name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - feature-branch
  pull_request:
    branches:
      - main
      - feature-branch

jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v2

  python-setup:
    runs-on: ubuntu-latest
    needs: code-checkout
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v2
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

  dependencies-install:
    runs-on: ubuntu-latest
    needs: python-setup
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v2
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Upgrade and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  code-lint:
    runs-on: ubuntu-latest
    needs: dependencies-install
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v2
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Upgrade and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
      - name: Run Linter
        run: |
          pip install flake8
          flake8 src

  run-tests:
    runs-on: ubuntu-latest
    needs: code-lint
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v2
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Upgrade and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
      - name: Execute Tests
        run: |
          pip install pytest flask-testing
          pytest

  docker-deploy:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v2

      - name: Display Secret Lengths
        run: |
          echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
          echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Authenticate Docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker Image
        run: docker build -t mlops59 .

      - name: Tag Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker tag mlops59:latest ${DOCKER_USERNAME}/mlops59:latest

      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push ${DOCKER_USERNAME}/mlops59:latest
